First, I will load the dataset from GBIF

In [1]:
import pandas as pd
data = pd.read_csv("./germplasm_banks/occurrence.txt", sep= "\t")
print(list(data.columns))

['gbifID', 'accessRights', 'bibliographicCitation', 'language', 'license', 'modified', 'publisher', 'references', 'rightsHolder', 'type', 'institutionID', 'collectionID', 'datasetID', 'institutionCode', 'collectionCode', 'datasetName', 'ownerInstitutionCode', 'basisOfRecord', 'informationWithheld', 'dataGeneralizations', 'dynamicProperties', 'occurrenceID', 'catalogNumber', 'recordNumber', 'recordedBy', 'recordedByID', 'individualCount', 'organismQuantity', 'organismQuantityType', 'sex', 'lifeStage', 'reproductiveCondition', 'caste', 'behavior', 'vitality', 'establishmentMeans', 'degreeOfEstablishment', 'pathway', 'georeferenceVerificationStatus', 'occurrenceStatus', 'preparations', 'disposition', 'associatedOccurrences', 'associatedReferences', 'associatedSequences', 'associatedTaxa', 'otherCatalogNumbers', 'occurrenceRemarks', 'organismID', 'organismName', 'organismScope', 'associatedOrganisms', 'previousIdentifications', 'organismRemarks', 'materialEntityID', 'materialEntityRemarks', 'verbatimLabel', 'materialSampleID', 'eventID', 'parentEventID', 'eventType', 'fieldNumber', 'eventDate', 'eventTime', 'startDayOfYear', 'endDayOfYear', 'year', 'month', 'day', 'verbatimEventDate', 'habitat', 'samplingProtocol', 'sampleSizeValue', 'sampleSizeUnit', 'samplingEffort', 'fieldNotes', 'eventRemarks', 'locationID', 'higherGeographyID', 'higherGeography', 'continent', 'waterBody', 'islandGroup', 'island', 'countryCode', 'stateProvince', 'county', 'municipality', 'locality', 'verbatimLocality', 'verbatimElevation', 'verticalDatum', 'verbatimDepth', 'minimumDistanceAboveSurfaceInMeters', 'maximumDistanceAboveSurfaceInMeters', 'locationAccordingTo', 'locationRemarks', 'decimalLatitude', 'decimalLongitude', 'coordinateUncertaintyInMeters', 'coordinatePrecision', 'pointRadiusSpatialFit', 'verbatimCoordinateSystem', 'verbatimSRS', 'footprintWKT', 'footprintSRS', 'footprintSpatialFit', 'georeferencedBy', 'georeferencedDate', 'georeferenceProtocol', 'georeferenceSources', 'georeferenceRemarks', 'geologicalContextID', 'earliestEonOrLowestEonothem', 'latestEonOrHighestEonothem', 'earliestEraOrLowestErathem', 'latestEraOrHighestErathem', 'earliestPeriodOrLowestSystem', 'latestPeriodOrHighestSystem', 'earliestEpochOrLowestSeries', 'latestEpochOrHighestSeries', 'earliestAgeOrLowestStage', 'latestAgeOrHighestStage', 'lowestBiostratigraphicZone', 'highestBiostratigraphicZone', 'lithostratigraphicTerms', 'group', 'formation', 'member', 'bed', 'identificationID', 'verbatimIdentification', 'identificationQualifier', 'typeStatus', 'identifiedBy', 'identifiedByID', 'dateIdentified', 'identificationReferences', 'identificationVerificationStatus', 'identificationRemarks', 'taxonID', 'scientificNameID', 'acceptedNameUsageID', 'parentNameUsageID', 'originalNameUsageID', 'nameAccordingToID', 'namePublishedInID', 'taxonConceptID', 'scientificName', 'acceptedNameUsage', 'parentNameUsage', 'originalNameUsage', 'nameAccordingTo', 'namePublishedIn', 'namePublishedInYear', 'higherClassification', 'kingdom', 'phylum', 'class', 'order', 'superfamily', 'family', 'subfamily', 'tribe', 'subtribe', 'genus', 'genericName', 'subgenus', 'infragenericEpithet', 'specificEpithet', 'infraspecificEpithet', 'cultivarEpithet', 'taxonRank', 'verbatimTaxonRank', 'vernacularName', 'nomenclaturalCode', 'taxonomicStatus', 'nomenclaturalStatus', 'taxonRemarks', 'datasetKey', 'publishingCountry', 'lastInterpreted', 'elevation', 'elevationAccuracy', 'depth', 'depthAccuracy', 'distanceFromCentroidInMeters', 'issue', 'taxonomicIssue', 'nonTaxonomicIssue', 'mediaType', 'hasCoordinate', 'hasGeospatialIssues', 'taxonKey', 'acceptedTaxonKey', 'kingdomKey', 'phylumKey', 'classKey', 'orderKey', 'familyKey', 'genusKey', 'subgenusKey', 'speciesKey', 'species', 'acceptedScientificName', 'verbatimScientificName', 'typifiedName', 'protocol', 'lastParsed', 'lastCrawled', 'isInvasive', 'repatriated', 'relativeOrganismQuantity', 'projectId', 'isSequenced', 'gbifRegion', 'publishedByGbifRegion', 'level0Gid', 'level0Name', 'level1Gid', 'level1Name', 'level2Gid', 'level2Name', 'level3Gid', 'level3Name', 'iucnRedListCategory']

# Germplasm
First, I do the mapping from GBIF's data to our CSV template.
As we only have data from GBIF at this point, all of the taxonomy reference column is filled with GBIF's taxonomy reference.
To create the contents of the iucn_threat_category cell, I have to add the rest of the URI to the category that is present in GBIF's dataset (e.g.: VU becomes http://rs.gbif.org/vocabulary/iucn/threat_status/VU)

In [2]:
germplasm = pd.DataFrame(columns=["uniqid", "accession_number", "national_catalogue_code", "taxon_identifier", "scientific_name", "scientific_name_authorship", "vernacular_name", "taxonomy_reference", "determination_status", "iucn_threat_category"])
germplasm[["accession_number", "taxon_identifier", "scientific_name", "vernacular_name"]] = data[["occurrenceID", "taxonID", "acceptedScientificName", "vernacularName"]]
germplasm["taxonomy_reference"] = "GBIF Secretariat: GBIF Backbone Taxonomy. https://doi.org/10.15468/39omei"
germplasm["iucn_threat_category"] = "http://rs.gbif.org/vocabulary/iucn/threat_status/" + data["iucnRedListCategory"]
germplasm

,uniqid,accession_number,national_catalogue_code,taxon_identifier,scientific_name,scientific_name_authorship,vernacular_name,taxonomy_reference,determination_status,iucn_threat_category
0,NaN,JBCLM:BGJBCLM:CM00013-08,NaN,NaN,Ziziphora aragonensis Pau,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
1,NaN,JBCLM:BGJBCLM:CM00009-08,NaN,NaN,Vella pseudocytisus subsp. pseudocytisus,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
2,NaN,JBCLM:BGJBCLM:CM00247-09,NaN,NaN,Zygophyllum fabago L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
3,NaN,JBCLM:BGJBCLM:CM00854-13,NaN,NaN,Viburnum lantana L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,http://rs.gbif.org/vocabulary/iucn/threat_stat...
4,NaN,JBCLM:BGJBCLM:CM00002-08,NaN,NaN,Ziziphora aragonensis Pau,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
903,NaN,JBCLM:BGJBCLM:CM00686-11,NaN,NaN,Anarrhinum fruticosum Desf.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
904,NaN,JBCLM:BGJBCLM:CM00243-09,NaN,NaN,Agrostemma githago L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
905,NaN,JBCLM:BGJBCLM:CM00591-11,NaN,NaN,Adonis vernalis L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
906,NaN,JBCLM:BGJBCLM:CM00629-11,NaN,NaN,Anarrhinum laxiflorum Boiss.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
907,NaN,JBCLM:BGJBCLM:CM00053-08,NaN,NaN,Andryala agardhii Haens. ex DC.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN

In [3]:
# Transform usageKey: Convert to Int64 and add URL prefix
def format_gbif_url(taxon_id):
    if pd.isna(taxon_id):
        return "N/A"
    try:
        return f"https://www.gbif.org/species/{int(taxon_id)}"
    except (ValueError, TypeError):
        return "N/A"

if germplasm["taxon_identifier"].isna().all() or (germplasm["taxon_identifier"] == "").all():
   germplasm["taxon_identifier"] = data["acceptedTaxonKey"].apply(format_gbif_url)
germplasm

,uniqid,accession_number,national_catalogue_code,taxon_identifier,scientific_name,scientific_name_authorship,vernacular_name,taxonomy_reference,determination_status,iucn_threat_category
0,NaN,JBCLM:BGJBCLM:CM00013-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis Pau,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
1,NaN,JBCLM:BGJBCLM:CM00009-08,NaN,https://www.gbif.org/species/7225676,Vella pseudocytisus subsp. pseudocytisus,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
2,NaN,JBCLM:BGJBCLM:CM00247-09,NaN,https://www.gbif.org/species/3189902,Zygophyllum fabago L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
3,NaN,JBCLM:BGJBCLM:CM00854-13,NaN,https://www.gbif.org/species/2888615,Viburnum lantana L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,http://rs.gbif.org/vocabulary/iucn/threat_stat...
4,NaN,JBCLM:BGJBCLM:CM00002-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis Pau,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
903,NaN,JBCLM:BGJBCLM:CM00686-11,NaN,https://www.gbif.org/species/8267849,Anarrhinum fruticosum Desf.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
904,NaN,JBCLM:BGJBCLM:CM00243-09,NaN,https://www.gbif.org/species/3085368,Agrostemma githago L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
905,NaN,JBCLM:BGJBCLM:CM00591-11,NaN,https://www.gbif.org/species/5371711,Adonis vernalis L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
906,NaN,JBCLM:BGJBCLM:CM00629-11,NaN,https://www.gbif.org/species/3742445,Anarrhinum laxiflorum Boiss.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
907,NaN,JBCLM:BGJBCLM:CM00053-08,NaN,https://www.gbif.org/species/3105500,Andryala agardhii Haens. ex DC.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN

Then, I will run the Taxonomic Name Resolution Service's (TNRS) API to transform the names to the World Flora Online Taxonomy. To do so, I first need to create a csv with IDs for each scientific name, as it is a requirement from the API

In [4]:
df2 = pd.DataFrame({
    "sciname": germplasm["scientific_name"].dropna().drop_duplicates()
})
df2.to_csv("./germplasm_banks/WFOAPI_input.csv", index = True, index_label="ID")

Then, I run the curl command to send my data to the API. The arguments that I've chosen are:
- -f: input file
- -o: output file
- -m: api mode. In this case, I've chosen resolve because it parses, matches to a published name and resolves names to accepted name.
- -s: taxonomic sources. In this case I only want to use WFO as taxonomic source.
- -k: keep files. Writes input and output as CSV files.

I had to modify the script that was provided to use the API (tnrsapi.sh), as it was passing all scientific names to be resolved as arguments in the curl command, exceeding the limit of characters in a command. I changed it to load from a file.

In [5]:
import subprocess
import os
script_path = "./tnrsapi.sh"
args = [
    "-f", "/home/acb8/Work/FLAIR-GG_models/germplasm_banks/WFOAPI_input.csv",
    "-o", "/home/acb8/Work/FLAIR-GG_models/germplasm_banks/WFOAPI_input_resolved.csv",
    "-m", "resolve",
    "-s", "wfo",
    "-k"
]

try:
    result = subprocess.run(
        [script_path] + args,
        capture_output=True,
        text=True
    )
    print("Script output:")
    print(result.stdout)
    if result.stderr:
        print("Script errors:")
        print(result.stderr)
    if result.returncode == 0:
        print("Script ran successfully.")
        # Check if output CSV exists
        if os.path.exists("/home/acb8/Work/FLAIR-GG_models/germplasm_banks/WFOAPI_input_resolved.csv"):
            print("Output CSV generated successfully.")
        else:
            print("Output CSV not found.")
    else:
        print(f"Script failed with return code {result.returncode}.")
except FileNotFoundError:
    print("Error: tnrsapi.sh not found in current directory.")
except subprocess.CalledProcessError as e:
    print(f"Error running script: {e}")
    print(f"Errors: {e.stderr}")

Script output:

Names submitted:
|  ID | sciname                                                                                                     |
| --- | ----------------------------------------------------------------------------------------------------------- |
|   0 | Ziziphora aragonensis Pau                                                                                   |
|   1 | Vella pseudocytisus subsp. pseudocytisus                                                                    |
|   2 | Zygophyllum fabago L.                                                                                       |
|   3 | Viburnum lantana L.                                                                                         |
|   6 | Viola cazorlensis Gand.                                                                                     |
|   8 | Viburnum tinus L.                                                                                           |
|   9 | Veronica chamaepithyoides Lam.                                                                              |
|  10 | Thymus zygis subsp. sylvestris (Hoffmanns. & Link) Cout.                                                    |
|  11 | Gypsophila vaccaria (L.) Sm.                                                                                |
|  12 | Thymus zygis subsp. zygis                                                                                   |
|  13 | Veronica fruticans subsp. cantabrica Lainz                                                                  |
|  15 | Vella pseudocytisus subsp. paui Gómez-Campo                                                                 |
|  16 | Thymus pulegioides L.                                                                                       |
|  18 | Thymus vulgaris subsp. vulgaris                                                                             |
|  19 | Thymus zygis subsp. gracilis (Boiss.) R.Morales                                                             |
|  21 | Vaccinium myrtillus L.                                                                                      |
|  22 | Trollius europaeus L.                                                                                       |
|  28 | Viburnum opulus L.                                                                                          |
|  29 | Thymus vulgaris subsp. aestivus (Reut. ex Willk.) A.Bolòs & O.Bolòs                                         |
|  31 | Thymus membranaceus Boiss.                                                                                  |
|  32 | Thymus orospedanus Villar                                                                                   |
|  34 | Thymus moroderi Pau ex Martínez                                                                             |
|  36 | Vella spinosa Boiss.                                                                                        |
|  39 | Thymus leptophyllus subsp. leptophyllus                                                                     |
|  40 | Vella lucentina M.B.Crespo                                                                                  |
|  43 | Thymus mastigophorus Lacaita                                                                                |
|  44 | Thymus mastichina (L.) L.                                                                                   |
|  46 | Thymus piperella L.                                                                                         |
|  51 | Thymus serpylloides subsp. gadorensis (Pau) Jalas                                                           |
|  54 | Thymus longiflorus Boiss.                                                                                   |
|  56 | Thymus funkii subsp. funkii                                                                                 |
|  58 | Thymus hyemalis Lange                                                                                       |
|  59 | Thymus funkii subsp. sabulicola (Coss.) Sánchez-Gómez                                                       |
|  63 | Thymus leptophyllus subsp. izcoi (Rivas Mart., A.Molina & G.Navarro) R.Morales                              |
|  64 | Thymus praecox subsp. britannicus (Ronniger) Holub                                                          |
|  67 | Thymus bracteatus Lange ex Cutanda                                                                          |
|  69 | Teucrium turredanum Losa & Rivas Goday                                                                      |
|  70 | Thymus antoninae Rouy & Coincy                                                                              |
|  72 | Thymus granatensis subsp. micranthus (Willk.) O.Bolòs & Vigo                                                |
|  73 | Thymus granatensis Boiss.                                                                                   |
|  76 | Thymus leptophyllus subsp. paui R.Morales                                                                   |
|  80 | Thlaspi arvense L.                                                                                          |
|  81 | Teucrium homotrichum (Font Quer) Rivas Mart.                                                                |
|  82 | Teucrium pseudochamaepitys L.                                                                               |
|  83 | Thymus loscosii Willk.                                                                                      |
|  85 | Teucrium libanitis Schreb.                                                                                  |
|  87 | Teucrium leonis Sennen                                                                                      |
|  88 | Teucrium scordium L.                                                                                        |
|  92 | Teucrium gnaphalodes L'Hér.                                                                                 |
|  94 | Teucrium chamaedrys L.                                                                                      |
|  95 | Teucrium expassum Pau                                                                                       |
|  96 | Teucrium rivas-martinezii Alcaraz, Garre, Mart.Parras & Peinado                                             |
|  97 | Teucrium murcicum Sennen                                                                                    |
| 100 | Teucrium haenseleri Boiss.                                                                                  |
| 103 | Thymus baeticus Boiss. ex Lacaita                                                                           |
| 106 | Stipa offneri Breistr.                                                                                      |
| 107 | Teucrium dunense Sennen                                                                                     |
| 108 | Teucrium capitatum subsp. capitatum                                                                         |
| 109 | Thalictrum simplex subsp. simplex                                                                           |
| 111 | Tanacetum corymbosum (L.) Sch.Bip.                                                                          |
| 112 | Stipa iberica Martinovský                                                                                   |
| 113 | Teucrium carthaginense Lange                                                                                |
| 114 | Teucrium rotundifolium Schreb.                                                                              |
| 115 | Suaeda vera Forssk. ex J.F.Gmel.                                                                            |
| 116 | Teucrium oxylepis Font Quer                                                                                 |
| 117 | Stachys recta L.                                                                                            |
| 118 | Solanum dulcamara L.                                                                                        |
| 119 | Achnatherum parviflorum (Desf.) M.Nobis                                                                     |
| 120 | Spiraea hypericifolia subsp. obovata (Waldst. & Kit. ex Willd.) H.Huber                                     |
| 121 | Genista patens DC.                                                                                          |
| 123 | Tanacetum vahlii DC.                                                                                        |
| 124 | Teucrium capitatum subsp. gracillimum (Rouy) Valdés Berm.                                                   |
| 127 | Betonica officinalis L.                                                                                     |
| 129 | Celtica gigantea (Link) F.M.Vázquez & Barkworth                                                             |
| 130 | Sorbus aucuparia L.                                                                                         |
| 131 | Sinapis alba L.                                                                                             |
| 133 | Cormus domestica (L.) Spach                                                                                 |
| 134 | Sinapis arvensis L.                                                                                         |
| 135 | Sisymbrium orientale L.                                                                                     |
| 138 | Sisymbrium hispanicum Jacq.                                                                                 |
| 139 | Teucrium carolipaui subsp. fontqueri (Sennen) Rivas Mart.                                                   |
| 143 | Silene muscipula L.                                                                                         |
| 144 | Silene conica L.                                                                                            |
| 145 | Sideritis tragoriganum subsp. tragoriganum                                                                  |
| 146 | Sisymbrium cavanillesianum Castrov. & Valdés Berm.                                                          |
| 148 | Aria edulis (Willd.) M.Roem.                                                                                |
| 149 | Sisymbrium runcinatum Lag. ex DC.                                                                           |
| 151 | Silene nutans L.                                                                                            |
| 152 | Stachys heraclea All.                                                                                       |
| 153 | Silene latifolia Poir.                                                                                      |
| 154 | Silene vulgaris subsp. vulgaris                                                                             |
| 155 | Silene andryalifolia Pomel                                                                                  |
| 156 | Sideritis serrata Lag.                                                                                      |
| 157 | Torminalis glaberrima (Gand.) Sennikov & Kurtto                                                             |
| 158 | Sideritis spinulosa Barnadez ex Asso                                                                        |
| 159 | Silene boryi Boiss.                                                                                         |
| 161 | Sideritis stachydioides Willk.                                                                              |
| 163 | Smyrnium perfoliatum L.                                                                                     |
| 166 | Sideritis pungens Benth.                                                                                    |
| 169 | Sideritis pauli Pau                                                                                         |
| 175 | Silene hifacensis Rouy                                                                                      |
| 177 | Sideritis pusilla (Lange) Pau                                                                               |
| 181 | Sideritis lacaitae Font Quer                                                                                |
| 182 | Sideritis lasiantha Juss. ex Pers.                                                                          |
| 184 | Silene ciliata Pourr.                                                                                       |
| 186 | Sideritis osteoxylla (Pau ex Vicioso) Alcaraz, Peinado, Mart.Parras, J.S.Carrion & Sánchez-Gómez            |
| 188 | Sideritis leucantha subsp. leucantha                                                                        |
| 189 | Sideritis laxespicata (Degen & Debeaux) Socorro, I.Tarrega & Zafra                                          |
| 190 | Sideritis leucantha subsp. incana (Willk.) Alcaraz, Peinado, Mart.Parras, J.S.Carrion & Sánchez-Gómez, 1987 |
| 192 | Sideritis incana L.                                                                                         |
| 196 | Sideritis hyssopifolia L.                                                                                   |
| 199 | Sideritis leucantha Cav.                                                                                    |
| 203 | Sideritis incana subsp. incana                                                                              |
| 206 | Sideritis chamaedryfolia Cav.                                                                               |
| 209 | Sideritis fruticulosa Pourr.                                                                                |
| 213 | Sideritis montserratiana Stübing, Roselló, Olivares & Peris                                                 |
| 215 | Senecio doria L.                                                                                            |
| 216 | Sideritis bourgaeana Boiss. & Reut.                                                                         |
| 217 | Sideritis hirsuta L.                                                                                        |
| 219 | Sideritis glauca Cav.                                                                                       |
| 220 | Sideritis glacialis Boiss.                                                                                  |
| 224 | Sideritis carbonellii Socorro                                                                               |
| 226 | Sideritis hyssopifolia subsp. hyssopifolia                                                                  |
| 229 | Senecio auricula Bourgeau ex Coss.                                                                          |
| 231 | Schoenoplectus tabernaemontani (C.C.Gmel.) Palla                                                            |
| 232 | Sideritis L.                                                                                                |
| 234 | Bolboschoenus maritimus (L.) Palla                                                                          |
| 237 | Sideritis arborescens Salzm. ex Benth.                                                                      |
| 240 | Saxifraga moncayensis D.A.Webb                                                                              |
| 241 | Scilla L.                                                                                                   |
| 242 | Scrophularia canina L.                                                                                      |
| 244 | Pseudopodospermum reverchonii (Debeaux & Hervier) Zaika, Sukhor. & N.Kilian                                 |
| 247 | Schoenus nigricans L.                                                                                       |
| 249 | Schoenoplectus lacustris (L.) Palla                                                                         |
| 254 | Santolina chamaecyparissus L.                                                                               |
| 255 | Saponaria officinalis L.                                                                                    |
| 256 | Salvia blancoana subsp. vellerea (Cuatrec.) W.Lippert                                                       |
| 258 | Sambucus nigra L.                                                                                           |
| 262 | Salvia officinalis subsp. lavandulifolia (Vahl) Gams                                                        |
| 264 | Saxifraga willkommiana subsp. willkommiana                                                                  |
| 265 | Salvia verbenaca L.                                                                                         |
| 266 | Sambucus ebulus L.                                                                                          |
| 267 | Salvia officinalis subsp. oxyodon (Webb & Heldr.) Reales, D.Rivera & Obón                                   |
| 270 | Salvia pratensis L.                                                                                         |
| 273 | Salvia phlomoides subsp. phlomoides                                                                         |
| 275 | Satureja intricata Lange                                                                                    |
| 278 | Salvia sclarea L.                                                                                           |
| 281 | Santolina viscosa Lag.                                                                                      |
| 282 | Ruta montana (L.) L.                                                                                        |
| 284 | Saxifraga cuneata Willd.                                                                                    |
| 287 | Salvia argentea L.                                                                                          |
| 288 | Salvia aethiopis L.                                                                                         |
| 291 | Ruta angustifolia Pers.                                                                                     |
| 292 | Rubus ulmifolius Schott                                                                                     |
| 294 | Salvia candelabrum Boiss.                                                                                   |
| 296 | Rumex crispus L.                                                                                            |
| 297 | Rosa spinosissima L.                                                                                        |
| 299 | Salvia rosmarinus Spenn.                                                                                    |
| 302 | Salvia blancoana Webb & Heldr.                                                                              |
| 304 | Ribes uva-crispa L.                                                                                         |
| 305 | Rosa canina L.                                                                                              |
| 307 | Reseda undata subsp. undata                                                                                 |
| 311 | Salvia blancoana subsp. mariolensis Figuerola                                                               |
| 312 | Rhamnus cathartica L.                                                                                       |
| 313 | Rosa pulverulenta M.Bieb.                                                                                   |
| 314 | Retama sphaerocarpa (L.) Boiss.                                                                             |
| 315 | Ribes alpinum L.                                                                                            |

Now I create a dataframe with the matches (dfWFO), and fill it with the results from the API matching. If there is an accepted name (i.e.: if the "Taxonomic_status" is Accepted or Synonym), that's what will be used, but if the "Taxonomic_status" is No opinion, then those columns are emtpy, so I will used the name that was matched from the WFO taxonomy. The same happens for the taxon identifier and authorship.

Note: there are less matches than rows because some are repeated

In [6]:
import numpy as np
dfWFO = pd.read_csv("/home/acb8/Work/FLAIR-GG_models/germplasm_banks/WFOAPI_input_resolved.csv")
dfWFO["scientific_name"] = np.where(
    dfWFO["Accepted_name"].notna() & (dfWFO["Accepted_name"] != ""),
    dfWFO["Accepted_name"],
    dfWFO["Name_matched"]
)
dfWFO["taxon_identifier"] = np.where(
    dfWFO["Accepted_name_url"].notna() & (dfWFO["Accepted_name_url"] != ""),
    dfWFO["Accepted_name_url"],
    dfWFO["Name_matched_url"]
)

dfWFO["scientific_name_authorship"] = np.where(
    dfWFO["Accepted_name_author"].notna() & (dfWFO["Accepted_name_author"] != ""),
    dfWFO["Accepted_name_author"],
    dfWFO["Canonical_author"]
)
dfWFO = dfWFO[["Name_submitted", "Author_submitted", "scientific_name", "taxon_identifier", "scientific_name_authorship"]]

dfWFO

,Name_submitted,Author_submitted,scientific_name,taxon_identifier,scientific_name_authorship
0,Ziziphora aragonensis Pau,Pau,Ziziphora aragonensis,https://www.worldfloraonline.org/taxon/wfo-000...,Pau
1,Vella pseudocytisus subsp. pseudocytisus,NaN,Vella pseudocytisus,https://www.worldfloraonline.org/taxon/wfo-000...,L.
2,Zygophyllum fabago L.,L.,Zygophyllum fabago,https://www.worldfloraonline.org/taxon/wfo-000...,L.
3,Viburnum lantana L.,L.,Viburnum lantana,https://www.worldfloraonline.org/taxon/wfo-000...,L.
4,Viola cazorlensis Gand.,Gand.,Viola cazorlensis,https://www.worldfloraonline.org/taxon/wfo-000...,Gand.
...,...,...,...,...,...
507,Aconitum napellus subsp. napellus,NaN,Aconitum napellus,https://www.worldfloraonline.org/taxon/wfo-000...,L.
508,Anarrhinum fruticosum Desf.,Desf.,Anarrhinum fruticosum,https://www.worldfloraonline.org/taxon/wfo-000...,Desf.
509,Agrostemma githago L.,L.,Agrostemma githago,https://www.worldfloraonline.org/taxon/wfo-000...,L.
510,Adonis vernalis L.,L.,Adonis vernalis,https://www.worldfloraonline.org/taxon/wfo-000...,L.
511,Anarrhinum laxiflorum Boiss.,Boiss.,Anarrhinum laxiflorum,https://www.worldfloraonline.org/taxon/wfo-000...,Boiss.

One of the benefits of the API is that it splits the name you submit from its authorship ("Name_submitted" and "Author_submitted" respectively). The issue is that it doesn't return ONLY the scientific name, so I'll remove the contents of the Author_submitted column from the Name_submitted column to get only the scientific name.

Now, to include the information from the germplasm banks in the entries of the new names, I have to match the "Name_submitted" column from dfWFO with "scientific_name" from the original gemrplasm df. The issue is that the API returns the Name_submitted column with the diacritics (non-ascii characters) and commas removed, so I have to do some preprocessing before merging both dataframes so that the germplasm["scientific_name"] and dfWFO["Name_submitted"] columns match.

In [7]:
print(list([germplasm["scientific_name"][0], dfWFO["Name_submitted"][0]]))

['Ziziphora aragonensis Pau', 'Ziziphora aragonensis Pau']

In [8]:
import unicodedata
# Function to remove diacritics
def remove_diacritics(text):
    if pd.isna(text):
        return text
    # Normalize to decomposed form (separate character and diacritic)
    normalized = unicodedata.normalize('NFD', str(text))
    # Remove non-ASCII characters (diacritics)
    return ''.join(c for c in normalized if unicodedata.category(c) != 'Mn').strip()
    
germplasm["temp_sci_name"] = germplasm["scientific_name"].apply(remove_diacritics)
#replace commas with space
germplasm["temp_sci_name"] = germplasm["temp_sci_name"].str.replace(',', ' ', regex=False)

In [9]:
dfWFO["Name_submitted"][5]

'Viburnum tinus L.'

In [10]:
dfWFO["Name_submitted"][5] == germplasm["temp_sci_name"].str.replace(',', ' ', regex=False)[15]

False

Now I'll merge both dataframes, using this temporary scientific name column (without the commas and diacritics) from the germplasm df and the "Name_submitted" column from the dfWFO df. If column names coincide, they will be tagged with their original dataframe to avoid confusion or loss of information

In [11]:
merged_df = pd.merge(germplasm, dfWFO, left_on = "temp_sci_name", right_on = "Name_submitted", how = "inner", suffixes = ("_germplasm", "_wfo"))
merged_df

,uniqid,accession_number,national_catalogue_code,taxon_identifier_germplasm,scientific_name_germplasm,scientific_name_authorship_germplasm,vernacular_name,taxonomy_reference,determination_status,iucn_threat_category,temp_sci_name,Name_submitted,Author_submitted,scientific_name_wfo,taxon_identifier_wfo,scientific_name_authorship_wfo
0,NaN,JBCLM:BGJBCLM:CM00013-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis Pau,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Ziziphora aragonensis Pau,Ziziphora aragonensis Pau,Pau,Ziziphora aragonensis,https://www.worldfloraonline.org/taxon/wfo-000...,Pau
1,NaN,JBCLM:BGJBCLM:CM00009-08,NaN,https://www.gbif.org/species/7225676,Vella pseudocytisus subsp. pseudocytisus,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Vella pseudocytisus subsp. pseudocytisus,Vella pseudocytisus subsp. pseudocytisus,NaN,Vella pseudocytisus,https://www.worldfloraonline.org/taxon/wfo-000...,L.
2,NaN,JBCLM:BGJBCLM:CM00247-09,NaN,https://www.gbif.org/species/3189902,Zygophyllum fabago L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Zygophyllum fabago L.,Zygophyllum fabago L.,L.,Zygophyllum fabago,https://www.worldfloraonline.org/taxon/wfo-000...,L.
3,NaN,JBCLM:BGJBCLM:CM00854-13,NaN,https://www.gbif.org/species/2888615,Viburnum lantana L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,http://rs.gbif.org/vocabulary/iucn/threat_stat...,Viburnum lantana L.,Viburnum lantana L.,L.,Viburnum lantana,https://www.worldfloraonline.org/taxon/wfo-000...,L.
4,NaN,JBCLM:BGJBCLM:CM00002-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis Pau,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Ziziphora aragonensis Pau,Ziziphora aragonensis Pau,Pau,Ziziphora aragonensis,https://www.worldfloraonline.org/taxon/wfo-000...,Pau
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902,NaN,JBCLM:BGJBCLM:CM00686-11,NaN,https://www.gbif.org/species/8267849,Anarrhinum fruticosum Desf.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Anarrhinum fruticosum Desf.,Anarrhinum fruticosum Desf.,Desf.,Anarrhinum fruticosum,https://www.worldfloraonline.org/taxon/wfo-000...,Desf.
903,NaN,JBCLM:BGJBCLM:CM00243-09,NaN,https://www.gbif.org/species/3085368,Agrostemma githago L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Agrostemma githago L.,Agrostemma githago L.,L.,Agrostemma githago,https://www.worldfloraonline.org/taxon/wfo-000...,L.
904,NaN,JBCLM:BGJBCLM:CM00591-11,NaN,https://www.gbif.org/species/5371711,Adonis vernalis L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Adonis vernalis L.,Adonis vernalis L.,L.,Adonis vernalis,https://www.worldfloraonline.org/taxon/wfo-000...,L.
905,NaN,JBCLM:BGJBCLM:CM00629-11,NaN,https://www.gbif.org/species/3742445,Anarrhinum laxiflorum Boiss.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Anarrhinum laxiflorum Boiss.,Anarrhinum laxiflorum Boiss.,Boiss.,Anarrhinum laxiflorum,https://www.worldfloraonline.org/taxon/wfo-000...,Boiss.
906,NaN,JBCLM:BGJBCLM:CM00053-08,NaN,https://www.gbif.org/species/3105500,Andryala agardhii Haens. ex DC.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Andryala agardhii Haens. ex DC.,Andryala agardhii Haens. ex DC.,Haens. ex DC.,Andryala agardhii,https://www.worldfloraonline.org/taxon/wfo-000...,Haens. ex DC.

In [12]:
merged_df = merged_df[["uniqid", "accession_number", "national_catalogue_code", "taxon_identifier_wfo", "scientific_name_wfo","scientific_name_authorship_wfo","vernacular_name", "taxonomy_reference", "determination_status", "iucn_threat_category"]]
merged_df["taxonomy_reference"] = "WFO (2025): World Flora Online. Published on the Internet; http://www.worldfloraonline.org"
merged_df.rename(columns={"taxon_identifier_wfo" : "taxon_identifier", "scientific_name_wfo" : "scientific_name", "scientific_name_authorship_wfo" : "scientific_name_authorship"}, inplace = True)
merged_df

/tmp/ipykernel_14499/411484739.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df["taxonomy_reference"] = "WFO (2025): World Flora Online. Published on the Internet; http://www.worldfloraonline.org"
/tmp/ipykernel_14499/411484739.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df.rename(columns={"taxon_identifier_wfo" : "taxon_identifier", "scientific_name_wfo" : "scientific_name", "scientific_name_authorship_wfo" : "scientific_name_authorship"}, inplace = True)

,uniqid,accession_number,national_catalogue_code,taxon_identifier,scientific_name,scientific_name_authorship,vernacular_name,taxonomy_reference,determination_status,iucn_threat_category
0,NaN,JBCLM:BGJBCLM:CM00013-08,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Ziziphora aragonensis,Pau,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
1,NaN,JBCLM:BGJBCLM:CM00009-08,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Vella pseudocytisus,L.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
2,NaN,JBCLM:BGJBCLM:CM00247-09,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Zygophyllum fabago,L.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
3,NaN,JBCLM:BGJBCLM:CM00854-13,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Viburnum lantana,L.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,http://rs.gbif.org/vocabulary/iucn/threat_stat...
4,NaN,JBCLM:BGJBCLM:CM00002-08,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Ziziphora aragonensis,Pau,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
902,NaN,JBCLM:BGJBCLM:CM00686-11,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Anarrhinum fruticosum,Desf.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
903,NaN,JBCLM:BGJBCLM:CM00243-09,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Agrostemma githago,L.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
904,NaN,JBCLM:BGJBCLM:CM00591-11,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Adonis vernalis,L.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
905,NaN,JBCLM:BGJBCLM:CM00629-11,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Anarrhinum laxiflorum,Boiss.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
906,NaN,JBCLM:BGJBCLM:CM00053-08,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Andryala agardhii,Haens. ex DC.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN

In [13]:
germplasm

,uniqid,accession_number,national_catalogue_code,taxon_identifier,scientific_name,scientific_name_authorship,vernacular_name,taxonomy_reference,determination_status,iucn_threat_category,temp_sci_name
0,NaN,JBCLM:BGJBCLM:CM00013-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis Pau,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Ziziphora aragonensis Pau
1,NaN,JBCLM:BGJBCLM:CM00009-08,NaN,https://www.gbif.org/species/7225676,Vella pseudocytisus subsp. pseudocytisus,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Vella pseudocytisus subsp. pseudocytisus
2,NaN,JBCLM:BGJBCLM:CM00247-09,NaN,https://www.gbif.org/species/3189902,Zygophyllum fabago L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Zygophyllum fabago L.
3,NaN,JBCLM:BGJBCLM:CM00854-13,NaN,https://www.gbif.org/species/2888615,Viburnum lantana L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,http://rs.gbif.org/vocabulary/iucn/threat_stat...,Viburnum lantana L.
4,NaN,JBCLM:BGJBCLM:CM00002-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis Pau,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Ziziphora aragonensis Pau
...,...,...,...,...,...,...,...,...,...,...,...
903,NaN,JBCLM:BGJBCLM:CM00686-11,NaN,https://www.gbif.org/species/8267849,Anarrhinum fruticosum Desf.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Anarrhinum fruticosum Desf.
904,NaN,JBCLM:BGJBCLM:CM00243-09,NaN,https://www.gbif.org/species/3085368,Agrostemma githago L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Agrostemma githago L.
905,NaN,JBCLM:BGJBCLM:CM00591-11,NaN,https://www.gbif.org/species/5371711,Adonis vernalis L.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Adonis vernalis L.
906,NaN,JBCLM:BGJBCLM:CM00629-11,NaN,https://www.gbif.org/species/3742445,Anarrhinum laxiflorum Boiss.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Anarrhinum laxiflorum Boiss.
907,NaN,JBCLM:BGJBCLM:CM00053-08,NaN,https://www.gbif.org/species/3105500,Andryala agardhii Haens. ex DC.,NaN,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN,Andryala agardhii Haens. ex DC.

Before concatenating the new rows with the WFO species, I have to split the original scientific names from GBIF into scientific name and authorhip, and the best, most reliable way to do so is through their species API, which I'll access using their pygbif library

In [14]:
import pandas as pd
from pygbif import species
import numpy as np

def get_full_authorship(scientific_name):
    # Handle empty, NaN, or non-string inputs
    if not isinstance(scientific_name, str) or not scientific_name.strip():
        return {"canonical_name": "N/A", "full_authorship": "N/A"}
    
    try:
        # Parse the name using GBIF
        result = species.name_parser(scientific_name)
        
        if not result or not result[0].get('parsed', False):
            return {"canonical_name": "N/A", "full_authorship": "N/A"}
        
        parsed_name = result[0]
        canonical_name = parsed_name.get('canonicalName', 'N/A')
        authorship = parsed_name.get('authorship', '')
        bracket_authorship = parsed_name.get('bracketAuthorship', '')
        
        # Construct full authorship
        if bracket_authorship:
            full_authorship = f"({bracket_authorship})"
            if authorship:
                full_authorship = f"{full_authorship} {authorship}"
        else:
            full_authorship = authorship if authorship else "N/A"
        
        return {
            "canonical_name": canonical_name,
            "full_authorship": full_authorship
        }
    except Exception as e:
        print(f"Error parsing {scientific_name}: {e}")
        return {"canonical_name": "N/A", "full_authorship": "N/A"}

# Process scientific names
germplasm_names = germplasm["scientific_name"].tolist()
name_only = []
author_only = []

for name in germplasm_names:
    result = get_full_authorship(name)
    name_only.append(result["canonical_name"])
    author_only.append(result["full_authorship"])

print(name_only)

['Ziziphora aragonensis', 'Vella pseudocytisus pseudocytisus', 'Zygophyllum fabago', 'Viburnum lantana', 'Ziziphora aragonensis', 'Ziziphora aragonensis', 'Viola cazorlensis', 'Ziziphora aragonensis', 'Viburnum tinus', 'Veronica chamaepithyoides', 'Thymus zygis sylvestris', 'Gypsophila vaccaria', 'Thymus zygis zygis', 'Veronica fruticans cantabrica', 'Thymus zygis sylvestris', 'Vella pseudocytisus paui', 'Thymus pulegioides', 'Thymus zygis zygis', 'Thymus vulgaris vulgaris', 'Thymus zygis gracilis', 'Thymus zygis sylvestris', 'Vaccinium myrtillus', 'Trollius europaeus', 'Thymus zygis gracilis', 'Trollius europaeus', 'Thymus zygis zygis', 'Vella pseudocytisus pseudocytisus', 'Thymus vulgaris vulgaris', 'Viburnum opulus', 'Thymus vulgaris aestivus', 'Thymus zygis gracilis', 'Thymus membranaceus', 'Thymus orospedanus', 'Viburnum lantana', 'Thymus moroderi', 'Thymus vulgaris vulgaris', 'Vella spinosa', 'Thymus membranaceus', 'Thymus pulegioides', 'Thymus leptophyllus leptophyllus', 'Vella lucentina', 'Thymus moroderi', 'Trollius europaeus', 'Thymus mastigophorus', 'Thymus mastichina', 'Thymus membranaceus', 'Thymus piperella', 'Thymus membranaceus', 'Thymus orospedanus', 'Thymus orospedanus', 'Thymus moroderi', 'Thymus serpylloides gadorensis', 'Thymus mastichina', 'Thymus vulgaris vulgaris', 'Thymus longiflorus', 'Thymus membranaceus', 'Thymus funkii funkii', 'Thymus vulgaris vulgaris', 'Thymus hyemalis', 'Thymus funkii sabulicola', 'Thymus longiflorus', 'Thymus serpylloides gadorensis', 'Thymus funkii funkii', 'Thymus leptophyllus izcoi', 'Thymus praecox britannicus', 'Thymus orospedanus', 'Thymus funkii sabulicola', 'Thymus bracteatus', 'Thymus funkii funkii', 'Teucrium turredanum', 'Thymus antoninae', 'Thymus leptophyllus izcoi', 'Thymus granatensis micranthus', 'Thymus granatensis', 'Thymus granatensis micranthus', 'Thymus bracteatus', 'Thymus leptophyllus paui', 'Thymus bracteatus', 'Thymus mastichina', 'Thymus funkii funkii', 'Thlaspi arvense', 'Teucrium homotrichum', 'Teucrium pseudochamaepitys', 'Thymus loscosii', 'Thymus leptophyllus paui', 'Teucrium libanitis', 'Thymus antoninae', 'Teucrium leonis', 'Teucrium scordium', 'Thymus leptophyllus izcoi', 'Thymus hyemalis', 'Teucrium libanitis', 'Teucrium gnaphalodes', 'Teucrium leonis', 'Teucrium chamaedrys', 'Teucrium expassum', 'Teucrium rivas-martinezii', 'Teucrium murcicum', 'Teucrium libanitis', 'Teucrium murcicum', 'Teucrium haenseleri', 'Teucrium turredanum', 'Teucrium gnaphalodes', 'Thymus baeticus', 'Teucrium homotrichum', 'Teucrium chamaedrys', 'Stipa offneri', 'Teucrium dunense', 'Teucrium capitatum capitatum', 'Thalictrum simplex simplex', 'Thymus antoninae', 'Tanacetum corymbosum', 'Stipa iberica', 'Teucrium carthaginense', 'Teucrium rotundifolium', 'Suaeda vera', 'Teucrium oxylepis', 'Stachys recta', 'Solanum dulcamara', 'Achnatherum parviflorum', 'Spiraea hypericifolia obovata', 'Genista patens', 'Teucrium chamaedrys', 'Tanacetum vahlii', 'Teucrium capitatum gracillimum', 'Genista patens', 'Stachys recta', 'Betonica officinalis', 'Teucrium expassum', 'Celtica gigantea', 'Sorbus aucuparia', 'Sinapis alba', 'Teucrium chamaedrys', 'Cormus domestica', 'Sinapis arvensis', 'Sisymbrium orientale', 'Teucrium expassum', 'Solanum dulcamara', 'Sisymbrium hispanicum', 'Teucrium carolipaui fontqueri', 'Sisymbrium hispanicum', 'Teucrium capitatum capitatum', 'Sinapis alba', 'Silene muscipula', 'Silene conica', 'Sideritis tragoriganum tragoriganum', 'Sisymbrium cavanillesianum', 'Sisymbrium cavanillesianum', 'Aria edulis', 'Sisymbrium runcinatum', 'Sisymbrium cavanillesianum', 'Silene nutans', 'Stachys heraclea', 'Silene latifolia', 'Silene vulgaris vulgaris', 'Silene andryalifolia', 'Sideritis serrata', 'Torminalis glaberrima', 'Sideritis spinulosa', 'Silene boryi', 'Aria edulis', 'Sideritis stachydioides', 'Sideritis tragoriganum tragoriganum', 'Smyrnium perfoliatum', 'Sideritis spinulosa', 'Sideritis spinulosa', 'Sideritis pungens', 'Sideritis serrata', 'Sideritis spinulosa', 'Sideritis pauli', 'Sisymbrium cavanillesianum', 'Sideritis tragoriganum tragoriganum', 'Sideritis pungens', 'Sideritis spinulosa', 'Sideritis stachydioides', 'Silene hifacensis', 'Sideritis spinulosa', 'Sideritis pusilla', 'Sideritis pungens', 'Sideritis serrata', 'Sideritis pungens', 'Sideritis lacaitae', 'Sideritis lasiantha', 'Sideritis pungens', 'Silene ciliata', 'Sideritis tragoriganum tragoriganum', 'Sideritis osteoxylla', 'Sideritis tragoriganum tragoriganum', 'Sideritis leucantha leucantha', 'Sideritis laxespicata', 'Sideritis leucantha incana', 'Sideritis leucantha incana', 'Sideritis incana', 'Sideritis lasiantha', 'Sideritis spinulosa', 'Sideritis pauli', 'Sideritis hyssopifolia', 'Sideritis pungens', 'Sideritis incana', 'Sideritis leucantha', 'Sideritis incana', 'Sideritis leucantha leucantha', 'Sideritis leucantha', 'Sideritis incana incana', 'Sideritis lacaitae', 'Sideritis incana', 'Sideritis chamaedryfolia', 'Sideritis leucantha leucantha', 'Sideritis pauli', 'Sideritis fruticulosa', 'Sideritis hyssopifolia', 'Sideritis pungens', 'Sideritis incana', 'Sideritis montserratiana', 'Sideritis chamaedryfolia', 'Senecio doria', 'Sideritis bourgaeana', 'Sideritis hirsuta', 'Sideritis hirsuta', 'Sideritis glauca', 'Sideritis glacialis', 'Sideritis chamaedryfolia', 'Sideritis incana', 'Sideritis chamaedryfolia', 'Sideritis carbonellii', 'Sideritis bourgaeana', 'Sideritis hyssopifolia hyssopifolia', 'Sideritis hirsuta', 'Sideritis hirsuta', 'Senecio auricula', 'Senecio auricula', 'Schoenoplectus tabernaemontani', 'Sideritis', 'Sideritis hirsuta', 'Bolboschoenus maritimus', 'Senecio auricula', 'Sideritis incana', 'Sideritis arborescens', 'Sideritis hirsuta', 'Bolboschoenus maritimus', 'Saxifraga moncayensis', 'Scilla', 'Scrophularia canina', 'Bolboschoenus maritimus', 'Pseudopodospermum reverchonii', 'Schoenoplectus tabernaemontani', 'Pseudopodospermum reverchonii', 'Schoenus nigricans', 'Senecio auricula', 'Schoenoplectus lacustris', 'Pseudopodospermum reverchonii', 'Pseudopodospermum reverchonii', 'Pseudopodospermum reverchonii', 'Senecio auricula', 'Santolina chamaecyparissus', 'Saponaria officinalis', 'Salvia blancoana vellerea', 'Senecio auricula', 'Sambucus nigra', 'Senecio doria', 'Pseudopodospermum reverchonii', 'Scrophularia canina', 'Salvia officinalis lavandulifolia', 'Salvia blancoana vellerea', 'Saxifraga willkommiana willkommiana', 'Salvia verbenaca', 'Sambucus ebulus', 'Salvia officinalis oxyodon', 'Salvia officinalis oxyodon', 'Salvia blancoana vellerea', 'Salvia pratensis', 'Salvia officinalis oxyodon', 'Salvia blancoana vellerea', 'Salvia phlomoides phlomoides', 'Salvia officinalis oxyodon', 'Satureja intricata', 'Santolina chamaecyparissus', 'Salvia verbenaca', 'Salvia sclarea', 'Salvia officinalis lavandulifolia', 'Salvia officinalis lavandulifolia', 'Santolina viscosa', 'Ruta montana', 'Salvia officinalis lavandulifolia', 'Saxifraga cuneata', 'Salvia verbenaca', 'Sambucus nigra', 'Salvia argentea', 'Salvia aethiopis', 'Salvia officinalis oxyodon', 'Salvia officinalis lavandulifolia', 'Ruta angustifolia', 'Rubus ulmifolius', 'Salvia officinalis lavandulifolia', 'Salvia candelabrum', 'Salvia aethiopis', 'Rumex crispus', 'Rosa spinosissima', 'Salvia argentea', 'Salvia rosmarinus', 'Salvia officinalis lavandulifolia', 'Salvia officinalis lavandulifolia', 'Salvia blancoana', 'Salvia blancoana', 'Ribes uva-crispa', 'Rosa canina', 'Salvia officinalis lavandulifolia', 'Reseda undata undata', 'Ribes uva-crispa', 'Salvia officinalis lavandulifolia', 'Salvia officinalis lavandulifolia', 'Salvia blancoana mariolensis', 'Rhamnus cathartica', 'Rosa pulverulenta', 'Retama sphaerocarpa', 'Ribes alpinum', 'Reseda suffruticosa', 'Ribes alpinum', 'Reseda suffruticosa', 'Rhamnus lycioides', 'Reseda suffruticosa', 'Retama sphaerocarpa', 'Ptilostemon hispanicus', 'Punica granatum', 'Rhamnus cathartica', 'Rosa canina', 'Rhamnus saxatilis', 'Ribes uva-crispa', 'Rhamnus saxatilis', 'Prunella vulgaris', 'Prunus prostrata', 'Rorippa pyrenaica', 'Phyteuma spicatum', 'Prunella vulgaris', 'Ribes alpinum', 'Rosa micrantha', 'Rhus coriaria', 'Pulsatilla rubra', 'Pistacia lentiscus', 'Pinguicula mundi', 'Phyteuma spicatum', 'Drymocallis rupestris', 'Prangos trifida', 'Pistacia terebinthus', 'Phlomis composita', 'Phyla nodiflora minor', 'Achnatherum paradoxum', 'Phlomis purpurea', 'Phlomis purpurea', 'Pistacia lentiscus', 'Prunus prostrata', 'Prunella vulgaris', 'Platanus hispanica', 'Plantago sempervirens', 'Phlomis lychnitis', 'Prunella vulgaris', 'Phlomis lychnitis', 'Peganum harmala', 'Phlomis herba-venti', 'Primula veris', 'Prunus spinosa', 'Potentilla', 'Phlomis purpurea', 'Imperatoria hispanica', 'Periploca laevigata', 'Pedicularis sylvatica sylvatica', 'Phlomis crinita', 'Phillyrea angustifolia', 'Phlomis crinita', 'Pedicularis schizocalyx', 'Petrorhagia nanteuilii', 'Papaver rhoeas', 'Paeonia broteroi', 'Roemeria argemone', 'Phalaris aquatica', 'Phlomis lychnitis', 'Phlomis lychnitis', 'Phlomis crinita', 'Phillyrea angustifolia', 'Ornithogalum pyrenaicum', 'Osyris alba', 'Phlomis lychnitis', 'Ornithogalum pyrenaicum', 'Nepeta nepetella murcica', 'Phlomis herba-venti', 'Phlomis lychnitis', 'Phlomis crinita', 'Paeonia mascula', 'Nepeta nepetella murcica', 'Nepeta tuberosa', 'Nepeta nepetella aragonensis', 'Nepeta tuberosa', 'Nepeta nepetella aragonensis', 'Ornithogalum narbonense', 'Origanum vulgare virens', 'Nepeta cataria', 'Nepeta granatensis', 'Nepeta nepetella murcica', 'Nepeta nepetella aragonensis', 'Nepeta tuberosa', 'Osyris lanceolata', 'Nerium oleander', 'Ornithogalum pyrenaicum', 'Onobrychis conferta hispanica', 'Nepeta hispanica hispanica', 'Narcissus confusus', 'Nepeta hispanica hispanica', 'Nepeta caerulea', 'Osyris alba', 'Onosma tricerosperma', 'Ornithogalum narbonense', 'Paeonia broteroi', 'Nepeta granatensis', 'Narcissus hedraeanthus', 'Narcissus hispanicus', 'Narcissus confusus', 'Narcissus', 'Narcissus hispanicus eugeniae', 'Narcissus yepesii', 'Narcissus yepesii', 'Narcissus hispanicus eugeniae', 'Narcissus hispanicus', 'Narcissus confusus', 'Narcissus hispanicus eugeniae', 'Narcissus nevadensis longispathus', 'Nepeta caerulea', 'Nepeta hispanica hispanica', 'Narcissus', 'Narcissus confusus', 'Minuartia mucronata', 'Narcissus bujei', 'Narcissus alcaracensis', 'Narcissus alcaracensis', 'Nepeta caerulea', 'Narcissus confusus', 'Nepeta caerulea', 'Narcissus hispanicus eugeniae', 'Nepeta hispanica hispanica', 'Molinia caerulea', 'Moricandia arvensis', 'Moricandia moricandioides', 'Microcnemum coralloides coralloides', 'Colchicum montanum', 'Myrtus communis', 'Narcissus alcaracensis', 'Mentha verticillata', 'Mentha cervina', 'Molinia caerulea', 'Microcnemum coralloides coralloides', 'Moricandia moricandioides', 'Narcissus bujei', 'Narcissus alcaracensis', 'Moricandia moricandioides', 'Muscari neglectum', 'Marrubium supinum', 'Mentha aquatica', 'Matthiola fruticulosa', 'Narcissus bujei', 'Mentha pulegium', 'Marrubium vulgare', 'Narcissus bujei', 'Narcissus alcaracensis', 'Chaerophyllum nodosum', 'Malva sylvestris', 'Marrubium supinum', 'Marrubium supinum', 'Marrubium supinum', 'Lysimachia vulgaris', 'Malus sylvestris', 'Marrubium vulgare', 'Lythrum salicaria', 'Mentha aquatica', 'Marrubium supinum', 'Marrubium supinum', 'Marrubium supinum', 'Malva moschata', 'Marrubium supinum', 'Marrubium supinum', 'Lythrum baeticum', 'Matthiola fruticulosa', 'Lonicera etrusca', 'Marrubium supinum', 'Lycopus europaeus', 'Matthiola fruticulosa', 'Lupinus hispanicus', 'Lonicera xylosteum', 'Lonicera etrusca', 'Marrubium vulgare', 'Lonicera etrusca', 'Mentha cervina', 'Lonicera etrusca', 'Lonicera periclymenum hispanica', 'Linum suffruticosum', 'Lomelosia simplex', 'Lonicera xylosteum', 'Linum appressum appressum', 'Lygeum spartum', 'Lonicera xylosteum', 'Lonicera etrusca', 'Lonicera etrusca', 'Lonicera arborea', 'Lonicera pyrenaica', 'Silene flos-cuculi', 'Lonicera periclymenum hispanica', 'Linum suffruticosum', 'Lepidium campestre', 'Lonicera xylosteum', 'Lycopus europaeus', 'Lonicera xylosteum', 'Linum bienne', 'Linaria hirta', 'Malva oblongifolia', 'Linaria hirta', 'Lepidium cardamine', 'Lysimachia ephemerum', 'Lepidium subulatum', 'Lavandula pedunculata', 'Coristospermum lucidum lucidum', 'Limonium pinillense', 'Lavandula stoechas stoechas', 'Lavandula stoechas stoechas', 'Limonium pinillense', 'Linum campanulatum', 'Lepidium subulatum', 'Leuzea conifera', 'Lavandula stoechas stoechas', 'Ligustrum vulgare', 'Ligustrum vulgare', 'Lavandula pedunculata', 'Linaria hirta', 'Lavandula latifolia', 'Lilium martagon', 'Limonium supinum', 'Linum bienne', 'Lavandula latifolia', 'Lavandula pedunculata', 'Lavandula latifolia', 'Lavandula stoechas luisieri', 'Lavandula pedunculata', 'Linum narbonense', 'Lavandula angustifolia pyrenaica', 'Lavandula latifolia', 'Lavandula latifolia', 'Lavandula pedunculata', 'Lavandula lanata', 'Lavandula dentata', 'Lavandula pedunculata', 'Lavandula pedunculata', 'Lavandula latifolia', 'Lavandula latifolia', 'Lavandula latifolia', 'Lavandula multifida', 'Lavandula angustifolia pyrenaica', 'Lavandula multifida', 'Lavandula pedunculata', 'Iris spuria', 'Lavandula pedunculata', 'Lavandula stoechas luisieri', 'Lavandula pedunculata', 'Iris pseudacorus', 'Juniperus oxycedrus oxycedrus', 'Juniperus sabina', 'Lavandula pedunculata', 'Isatis tinctoria', 'Chrysojasminum fruticans', 'Chrysojasminum fruticans', 'Juniperus oxycedrus oxycedrus', 'Iberis saxatilis cinerea', 'Pentanema helenioides', 'Juniperus communis communis', 'Ilex aquifolium', 'Juncus squarrosus', 'Juniperus thurifera', 'Jasione crispa crispa', 'Inula helenium', 'Chiliadenus glutinosus', 'Chrysojasminum fruticans', 'Ilex aquifolium', 'Chrysojasminum fruticans', 'Juniperus oxycedrus oxycedrus', 'Juncus', 'Juniperus oxycedrus badia', 'Juniperus phoenicea phoenicea', 'Helianthemum squamatum', 'Helianthemum polygonoides', 'Jurinea humilis', 'Iberis pectinata', 'Hyssopus officinalis', 'Helianthemum violaceum', 'Hirschfeldia incana', 'Helleborus foetidus', 'Hypericum veronense', 'Helianthemum ledifolium', 'Helianthemum hirtum', 'Hyoscyamus niger', 'Helianthemum hirtum', 'Hyoscyamus albus', 'Iberis pectinata', 'Helleborus foetidus', 'Helianthemum polygonoides', 'Hormathophylla spinosa', 'Heracleum sphondylium', 'Helianthemum hirtum', 'Hormathophylla spinosa', 'Iberis contracta', 'Hyoscyamus albus', 'Hypericum perforatum', 'Iberis contracta', 'Halimium atriplicifolium', 'Halimium atriplicifolium', 'Helianthemum guerrae', 'Helianthemum guerrae', 'Iberis saxatilis cinerea', 'Halimium atriplicifolium', 'Halimium umbellatum viscosum', 'Cistus halimifolius halimifolius', 'Helianthemum guerrae', 'Halimium atriplicifolium', 'Helianthemum asperum', 'Gypsophila struthium hispanica', 'Gypsophila struthium struthium', 'Helianthemum guerrae', 'Helianthemum apenninum', 'Cistus halimifolius halimifolius', 'Halimium atriplicifolium', 'Haplophyllum linifolium', 'Halimium ocymoides', 'Gypsophila struthium struthium', 'Halimium umbellatum viscosum', 'Helianthemum guerrae', 'Hedysarum boveanum europaeum', 'Helianthemum croceum', 'Helianthemum guerrae', 'Genista cinerea', 'Genista cinerea', 'Thapsia scabra', 'Gypsophila bermejoi', 'Helianthemum hirtum', 'Genista florida', 'Globularia vulgaris', 'Genista umbellata', 'Genista scorpius', 'Fumana scoparia', 'Gladiolus illyricus', 'Fraxinus angustifolia angustifolia', 'Fraxinus ornus', 'Gypsophila pilosa', 'Genista mugronensis rigidissima', 'Geum hispidum', 'Genista anglica', 'Gentiana lutea', 'Genista spartioides', 'Fraxinus angustifolia oxycarpa', 'Genista umbellata', 'Glaucium corniculatum', 'Gypsophila bermejoi', 'Gentiana lutea', 'Gypsophila bermejoi', 'Erica cinerea', 'Epilobium hirsutum', 'Gypsophila pilosa', 'Erucastrum nasturtiifolium', 'Erysimum repandum', 'Erysimum myriophyllum', 'Erica vagans', 'Eupatorium cannabinum', 'Eriophorum latifolium', 'Diplotaxis virgata', 'Echium boissieri', 'Echinospartum boissieri', 'Filipendula vulgaris', 'Erysimum nevadense gomez-campoi', 'Erinacea anthyllis', 'Ephedra fragilis fragilis', 'Erysimum incanum incanum', 'Eruca vesicaria', 'Erysimum cazorlense', 'Dittrichia viscosa', 'Erysimum cazorlense', 'Erysimum nevadense mediohispanicum', 'Euonymus europaeus', 'Erysimum incanum incanum', 'Euonymus latifolius', 'Delphinium fissum sordidum', 'Datura stramonium', 'Frangula alnus', 'Delphinium fissum sordidum', 'Digitalis obscura', 'Digitalis obscura', 'Delphinium fissum sordidum', 'Digitalis purpurea', 'Cytisus fontanesii', 'Delphinium fissum sordidum', 'Daphne gnidium', 'Cytisus scoparius scoparius', 'Digitalis thapsi', 'Dictamnus hispanicus', 'Delphinium fissum sordidum', 'Datura stramonium', 'Dianthus lusitanus', 'Dianthus pungens brachyanthus', 'Delphinium fissum sordidum', 'Cytisus scoparius reverchonii', 'Descurainia sophia', 'Dictamnus hispanicus', 'Digitalis obscura', 'Dianthus broteri', 'Digitalis purpurea', 'Coronilla juncea', 'Cotoneaster granatensis', 'Coronilla valentina glauca', 'Diplotaxis harra crassifolia', 'Crataegus monogyna', 'Crataegus monogyna', 'Coronilla minima lotoides', 'Cytisophyllum sessilifolium', 'Delphinium ajacis', 'Lepidium navasii', 'Cornus sanguinea sanguinea', 'Cornus sanguinea sanguinea', 'Cytisus fontanesii', 'Crataegus monogyna', 'Coronilla minima minima', 'Coronilla valentina glauca', 'Crataegus laciniata', 'Lepidium navasii', 'Cotoneaster tomentosus', 'Convolvulus lanuginosus', 'Cotoneaster tomentosus', 'Crataegus monogyna', 'Silene baccifera', 'Crataegus laciniata', 'Cynosurus cristatus', 'Coincya rupestris leptocarpa', 'Coincya rupestris leptocarpa', 'Coincya rupestris rupestris', 'Cytisus fontanesii', 'Colutea arborescens hispanica', 'Coincya rupestris leptocarpa', 'Colutea brevialata', 'Conium maculatum', 'Coincya monensis orophila', 'Coincya longirostra', 'Coincya monensis orophila', 'Coincya rupestris leptocarpa', 'Conopodium pyrenaeum', 'Colutea arborescens', 'Coincya rupestris leptocarpa', 'Coincya rupestris leptocarpa', 'Coincya monensis orophila', 'Coincya rupestris rupestris', 'Coincya rupestris rupestris', 'Coincya monensis orophila', 'Coincya rupestris rupestris', 'Colutea arborescens', 'Colutea arborescens hispanica', 'Coincya rupestris rupestris', 'Colutea arborescens hispanica', 'Cladium mariscus', 'Clematis viticella', 'Cladium mariscus', 'Delphinium ajacis', 'Coincya longirostra', 'Cistus salviifolius', 'Coincya longirostra', 'Cladium mariscus', 'Cistus salviifolius', 'Coincya longirostra', 'Cistus populifolius', 'Clematis recta', 'Clinopodium vulgare', 'Coincya longirostra', 'Cladium mariscus', 'Clematis vitalba', 'Cistus salviifolius', 'Clinopodium vulgare', 'Cistus', 'Cleonia lusitanica', 'Ionopsidium glastifolium', 'Coincya longirostra', 'Cleonia lusitanica', 'Cleonia lusitanica', 'Coincya longirostra', 'Chaenorhinum crassifolium crassifolium', 'Chaerophyllum aureum', 'Cistus albidus', 'Coincya longirostra', 'Cistus ladanifer', 'Cistus clusii', 'Carex hispida', 'Cistus monspeliensis', 'Carrichtera annua', 'Cirsium rosulatum', 'Chaerophyllum aureum', 'Cistus creticus', 'Trocdaris verticillatum', 'Cistus monspeliensis', 'Chenopodium album', 'Cistus albidus', 'Rhaponticoides alpina', 'Cistus clusii', 'Carex hispida', 'Cistus', 'Cistus clusii', 'Cistus laurifolius', 'Cistus albidus', 'Cistus', 'Cistus libanotis', 'Brachypodium phoenicoides', 'Cistus populifolius', 'Brachypodium sylvaticum', 'Brassica repanda africana', 'Bupleurum fruticosum', 'Camelina microcarpa', 'Bellardia trixago', 'Capparis spinosa', 'Brassica repanda gypsicola', 'Brassica napus', 'Berberis hispanica seroi', 'Berberis hispanica seroi', 'Bupleurum rotundifolium', 'Carex davalliana', 'Brassica repanda gypsicola', 'Brassica repanda gypsicola', 'Betula pendula pendula', 'Bupleurum fruticescens fruticescens', 'Berberis hispanica hispanica', 'Bupleurum fruticescens fruticescens', 'Campanula latifolia', 'Bupleurum fruticosum', 'Bromus diandrus', 'Bupleurum fruticescens fruticescens', 'Camphorosma monspeliaca', 'Carex echinata', 'A

In [15]:
germplasm = germplasm.drop(columns=["temp_sci_name"])
germplasm["scientific_name"] = name_only
germplasm["scientific_name_authorship"] = author_only
germplasm

,uniqid,accession_number,national_catalogue_code,taxon_identifier,scientific_name,scientific_name_authorship,vernacular_name,taxonomy_reference,determination_status,iucn_threat_category
0,NaN,JBCLM:BGJBCLM:CM00013-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis,Pau,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
1,NaN,JBCLM:BGJBCLM:CM00009-08,NaN,https://www.gbif.org/species/7225676,Vella pseudocytisus pseudocytisus,N/A,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
2,NaN,JBCLM:BGJBCLM:CM00247-09,NaN,https://www.gbif.org/species/3189902,Zygophyllum fabago,L.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
3,NaN,JBCLM:BGJBCLM:CM00854-13,NaN,https://www.gbif.org/species/2888615,Viburnum lantana,L.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,http://rs.gbif.org/vocabulary/iucn/threat_stat...
4,NaN,JBCLM:BGJBCLM:CM00002-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis,Pau,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
903,NaN,JBCLM:BGJBCLM:CM00686-11,NaN,https://www.gbif.org/species/8267849,Anarrhinum fruticosum,Desf.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
904,NaN,JBCLM:BGJBCLM:CM00243-09,NaN,https://www.gbif.org/species/3085368,Agrostemma githago,L.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
905,NaN,JBCLM:BGJBCLM:CM00591-11,NaN,https://www.gbif.org/species/5371711,Adonis vernalis,L.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
906,NaN,JBCLM:BGJBCLM:CM00629-11,NaN,https://www.gbif.org/species/3742445,Anarrhinum laxiflorum,Boiss.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
907,NaN,JBCLM:BGJBCLM:CM00053-08,NaN,https://www.gbif.org/species/3105500,Andryala agardhii,Haens. ex DC.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN

Now I will concatenate the rows with the WFO information to the original dataset

In [16]:
germplasm2 = pd.concat([germplasm, merged_df], ignore_index = True)
germplasm2

,uniqid,accession_number,national_catalogue_code,taxon_identifier,scientific_name,scientific_name_authorship,vernacular_name,taxonomy_reference,determination_status,iucn_threat_category
0,NaN,JBCLM:BGJBCLM:CM00013-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis,Pau,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
1,NaN,JBCLM:BGJBCLM:CM00009-08,NaN,https://www.gbif.org/species/7225676,Vella pseudocytisus pseudocytisus,N/A,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
2,NaN,JBCLM:BGJBCLM:CM00247-09,NaN,https://www.gbif.org/species/3189902,Zygophyllum fabago,L.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
3,NaN,JBCLM:BGJBCLM:CM00854-13,NaN,https://www.gbif.org/species/2888615,Viburnum lantana,L.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,http://rs.gbif.org/vocabulary/iucn/threat_stat...
4,NaN,JBCLM:BGJBCLM:CM00002-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis,Pau,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1810,NaN,JBCLM:BGJBCLM:CM00686-11,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Anarrhinum fruticosum,Desf.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
1811,NaN,JBCLM:BGJBCLM:CM00243-09,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Agrostemma githago,L.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
1812,NaN,JBCLM:BGJBCLM:CM00591-11,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Adonis vernalis,L.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
1813,NaN,JBCLM:BGJBCLM:CM00629-11,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Anarrhinum laxiflorum,Boiss.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
1814,NaN,JBCLM:BGJBCLM:CM00053-08,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Andryala agardhii,Haens. ex DC.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN

In [20]:
from datetime import datetime
import time
lista = []
for i in range(1, len(germplasm2["uniqid"])+1):
    now = datetime.now()
    now = now.strftime('%Y%m%d%H%M%S%f')
    lista.append(now)
    time.sleep(0.001)
germplasm2["uniqid"] = lista
germplasm2

,uniqid,accession_number,national_catalogue_code,taxon_identifier,scientific_name,scientific_name_authorship,vernacular_name,taxonomy_reference,determination_status,iucn_threat_category
0,20251007160019885752,JBCLM:BGJBCLM:CM00013-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis,Pau,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
1,20251007160019886954,JBCLM:BGJBCLM:CM00009-08,NaN,https://www.gbif.org/species/7225676,Vella pseudocytisus pseudocytisus,N/A,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
2,20251007160019888234,JBCLM:BGJBCLM:CM00247-09,NaN,https://www.gbif.org/species/3189902,Zygophyllum fabago,L.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
3,20251007160019889901,JBCLM:BGJBCLM:CM00854-13,NaN,https://www.gbif.org/species/2888615,Viburnum lantana,L.,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,http://rs.gbif.org/vocabulary/iucn/threat_stat...
4,20251007160019891680,JBCLM:BGJBCLM:CM00002-08,NaN,https://www.gbif.org/species/3899518,Ziziphora aragonensis,Pau,NaN,GBIF Secretariat: GBIF Backbone Taxonomy. http...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1810,20251007160022672771,JBCLM:BGJBCLM:CM00686-11,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Anarrhinum fruticosum,Desf.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
1811,20251007160022674376,JBCLM:BGJBCLM:CM00243-09,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Agrostemma githago,L.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
1812,20251007160022675811,JBCLM:BGJBCLM:CM00591-11,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Adonis vernalis,L.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
1813,20251007160022677297,JBCLM:BGJBCLM:CM00629-11,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Anarrhinum laxiflorum,Boiss.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN
1814,20251007160022679027,JBCLM:BGJBCLM:CM00053-08,NaN,https://www.worldfloraonline.org/taxon/wfo-000...,Andryala agardhii,Haens. ex DC.,NaN,WFO (2025): World Flora Online. Published on t...,NaN,NaN

In [24]:
germplasm2.to_csv("germplasm2.csv", index = False)

# Location

In [25]:
location = pd.DataFrame(columns=["uniqid", "accession_number", "national_catalogue_code", "acquisition_time", "collecting_time", "soil_type", "latitude", "longitude", "coordinate_uncertainty", "geodetic_datum", "maximum_elevation", "minimum_elevation", "terrain_inclination", "country_name", "country_2letter_code", "first_admin_subdivision", "second_admin_subdivision", "third_admin_subdivision", "fourth_admin_subdivision", "locality_description"])
location

Empty DataFrame
Columns: [uniqid, accession_number, national_catalogue_code, acquisition_time, collecting_time, soil_type, latitude, longitude, coordinate_uncertainty, geodetic_datum, maximum_elevation, minimum_elevation, terrain_inclination, country_name, country_2letter_code, first_admin_subdivision, second_admin_subdivision, third_admin_subdivision, fourth_admin_subdivision, locality_description]
Index: []

In [26]:
location[["accession_number", "collecting_time", "latitude", "longitude", "coordinate_uncertainty", "geodetic_datum", "maximum_elevation", "country_name", "country_2letter_code", "first_admin_subdivision", "second_admin_subdivision", "third_admin_subdivision", "fourth_admin_subdivision", "locality_description"]] = data[["occurrenceID", "eventDate", "decimalLatitude", "decimalLongitude", "coordinateUncertaintyInMeters", "verbatimCoordinateSystem", "elevation","level0Name", "countryCode", "stateProvince", "county", "municipality", "locality", "verbatimLocality"]]
location["minimum_elevation"] = location["maximum_elevation"]
location.head()

,uniqid,accession_number,national_catalogue_code,acquisition_time,collecting_time,soil_type,latitude,longitude,coordinate_uncertainty,geodetic_datum,maximum_elevation,minimum_elevation,terrain_inclination,country_name,country_2letter_code,first_admin_subdivision,second_admin_subdivision,third_admin_subdivision,fourth_admin_subdivision,locality_description
0,NaN,JBCLM:BGJBCLM:CM00013-08,NaN,NaN,2001-06-26,NaN,39.0700,-2.670000,NaN,NaN,NaN,NaN,NaN,Spain,ES,Albacete,NaN,NaN,Villarrobledo,NaN
1,NaN,JBCLM:BGJBCLM:CM00009-08,NaN,NaN,2006-07-14,NaN,39.9997,-3.529319,NaN,NaN,NaN,NaN,NaN,Spain,ES,Toledo,NaN,NaN,Ontigola,NaN
2,NaN,JBCLM:BGJBCLM:CM00247-09,NaN,NaN,2009-07-03,NaN,38.4900,-1.670000,NaN,NaN,NaN,NaN,NaN,Spain,ES,Albacete,NaN,NaN,Hellín,NaN
3,NaN,JBCLM:BGJBCLM:CM00854-13,NaN,NaN,2013-09-04,NaN,42.3218,-0.334900,NaN,NaN,NaN,NaN,NaN,Spain,ES,Huesca,NaN,NaN,Jaca,NaN
4,NaN,JBCLM:BGJBCLM:CM00002-08,NaN,NaN,1997-07-29,NaN,39.1500,-2.490000,NaN,NaN,NaN,NaN,NaN,Spain,ES,Albacete,NaN,NaN,Villarrobledo,NaN

In [27]:
from datetime import datetime
import time
lista = []
for i in range(1, len(location["uniqid"])+1):
    now = datetime.now()
    now = now.strftime('%Y%m%d%H%M%S%f')
    lista.append(now)
    time.sleep(0.001)
location["uniqid"] = lista
location

,uniqid,accession_number,national_catalogue_code,acquisition_time,collecting_time,soil_type,latitude,longitude,coordinate_uncertainty,geodetic_datum,maximum_elevation,minimum_elevation,terrain_inclination,country_name,country_2letter_code,first_admin_subdivision,second_admin_subdivision,third_admin_subdivision,fourth_admin_subdivision,locality_description
0,20251007160058109185,JBCLM:BGJBCLM:CM00013-08,NaN,NaN,2001-06-26,NaN,39.070000,-2.670000,NaN,NaN,NaN,NaN,NaN,Spain,ES,Albacete,NaN,NaN,Villarrobledo,NaN
1,20251007160058118840,JBCLM:BGJBCLM:CM00009-08,NaN,NaN,2006-07-14,NaN,39.999700,-3.529319,NaN,NaN,NaN,NaN,NaN,Spain,ES,Toledo,NaN,NaN,Ontigola,NaN
2,20251007160058120379,JBCLM:BGJBCLM:CM00247-09,NaN,NaN,2009-07-03,NaN,38.490000,-1.670000,NaN,NaN,NaN,NaN,NaN,Spain,ES,Albacete,NaN,NaN,Hellín,NaN
3,20251007160058121814,JBCLM:BGJBCLM:CM00854-13,NaN,NaN,2013-09-04,NaN,42.321800,-0.334900,NaN,NaN,NaN,NaN,NaN,Spain,ES,Huesca,NaN,NaN,Jaca,NaN
4,20251007160058131104,JBCLM:BGJBCLM:CM00002-08,NaN,NaN,1997-07-29,NaN,39.150000,-2.490000,NaN,NaN,NaN,NaN,NaN,Spain,ES,Albacete,NaN,NaN,Villarrobledo,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,20251007160059560666,JBCLM:BGJBCLM:CM00686-11,NaN,NaN,2011-06-28,NaN,38.263100,-0.799110,NaN,NaN,NaN,NaN,NaN,Spain,ES,Alicante,NaN,NaN,Crevillente,NaN
904,20251007160059562253,JBCLM:BGJBCLM:CM00243-09,NaN,NaN,2009-06-19,NaN,38.723359,-1.770983,NaN,NaN,NaN,NaN,NaN,Spain,ES,Albacete,NaN,NaN,Albacete,NaN
905,20251007160059563659,JBCLM:BGJBCLM:CM00591-11,NaN,NaN,2011-06-05,NaN,38.656240,-1.860258,NaN,NaN,NaN,NaN,NaN,Spain,ES,Albacete,NaN,NaN,Albacete,NaN
906,20251007160059565264,JBCLM:BGJBCLM:CM00629-11,NaN,NaN,2011-08-23,NaN,38.659700,-2.390000,NaN,NaN,NaN,NaN,NaN,Spain,ES,Albacete,NaN,NaN,Peñascosa,NaN
907,20251007160059566807,JBCLM:BGJBCLM:CM00053-08,NaN,NaN,1997-07-23,NaN,38.070000,-2.353000,NaN,NaN,NaN,NaN,NaN,Spain,ES,Albacete,NaN,NaN,Nerpio,NaN

In [29]:
location["latitude"]

0      39.070000
1      39.999700
2      38.490000
3      42.321800
4      39.150000
         ...
903    38.263100
904    38.723359
905    38.656240
906    38.659700
907    38.070000
Name: latitude, Length: 908, dtype: float64

In [28]:
location.to_csv("location.csv", index = False)